# Generated by Django 2.2 on 2020-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200411_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='color',
            field=models.CharField(default='red', max_length=15),
            preserve_default=False,
        ),
    ]
