# Generated by Django 2.2 on 2020-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.TimeField(default='1:00'),
            preserve_default=False,
        ),
    ]
