# Generated by Django 2.2 on 2020-05-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200506_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='office',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
