# Generated by Django 2.2 on 2020-05-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
