# Generated by Django 2.2 on 2020-05-08 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_reminders', models.BooleanField(default=False)),
                ('email_reminders', models.BooleanField(default=False)),
                ('new_appointment_notification', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('satisfaction_forms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Sex',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('alt_phone_number', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('cc', models.CharField(blank=True, max_length=15)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fav_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Staff')),
                ('rgpd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_rgpd', to='clients.RGPD')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sex', to='clients.Sex')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
