# Generated by Django 2.2 on 2020-04-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('data', models.DateField(auto_now=True)),
                ('rgpd', models.BooleanField()),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Sex')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
