# Generated by Django 2.2 on 2020-04-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name_plural': 'Sex'},
        ),
    ]
