# Generated by Django 2.2 on 2020-05-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_color'),
        ('clients', '0003_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alt_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cc',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='fav_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
