# Generated by Django 2.2 on 2020-05-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200504_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rgpd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.RGPD'),
            preserve_default=False,
        ),
    ]
