# Generated by Django 2.2 on 2020-05-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_rgpd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rgpd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_rgpd', to='clients.RGPD'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sex', to='clients.Sex'),
        ),
    ]
