# Generated by Django 2.2 on 2020-04-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nif', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owners.Owner')),
            ],
        ),
    ]
